export interface Category {
    id: string;
    name: string;
  }
  
export const categories: Category[] = [
    { id: '1', name: 'Electronics' },
    { id: '2', name: 'Fashion' },
    { id: '3', name: 'Home Appliances' },
    { id: '4', name: 'Books' },
    { id: '5', name: 'Toys' },
    { id: '6', name: 'Sports' },
    { id: '7', name: 'Beauty & Personal Care' },
    { id: '8', name: 'Automotive' },
    { id: '9', name: 'Groceries' },
    { id: '10', name: 'Health & Wellness' },
    { id: '11', name: 'Furniture' },
    { id: '12', name: 'Office Supplies' },
    { id: '13', name: 'Pet Supplies' },
    { id: '14', name: 'Garden & Outdoor' },
    { id: '15', name: 'Musical Instruments' },
    { id: '16', name: 'Baby Products' },
    { id: '17', name: 'Video Games' },
    { id: '18', name: 'Movies & TV' },
    { id: '19', name: 'Jewelry' },
    { id: '20', name: 'Watches' },
    { id: '21', name: 'Luggage & Travel Gear' },
    { id: '22', name: 'Crafts & Sewing' },
    { id: '23', name: 'Industrial & Scientific' },
    { id: '24', name: 'Software' },
    { id: '25', name: 'Cell Phones & Accessories' },
    { id: '26', name: 'Cameras & Photography' },
    { id: '27', name: 'Computers & Accessories' },
    { id: '28', name: 'Smart Home' },
    { id: '29', name: 'Tools & Home Improvement' },
    { id: '30', name: 'Kitchen & Dining' },
    { id: '31', name: 'Bedding' },
    { id: '32', name: 'Bath' },
    { id: '33', name: 'Lighting' },
    { id: '34', name: 'Rugs' },
    { id: '35', name: 'Art Supplies' },
    { id: '36', name: 'Party Supplies' },
    { id: '37', name: 'Costumes' },
    { id: '38', name: 'Seasonal Décor' },
    { id: '39', name: 'Collectibles' },
    { id: '40', name: 'Antiques' },
    { id: '41', name: 'Hobbies' },
    { id: '42', name: 'Board Games' },
    { id: '43', name: 'Card Games' },
    { id: '44', name: 'Puzzles' },
    { id: '45', name: 'Outdoor Recreation' },
    { id: '46', name: 'Camping & Hiking' },
    { id: '47', name: 'Cycling' },
    { id: '48', name: 'Fishing' },
    { id: '49', name: 'Hunting' },
    { id: '50', name: 'Water Sports' },
    { id: '51', name: 'Winter Sports' },
    { id: '52', name: 'Fitness Equipment' },
    { id: '53', name: 'Yoga & Pilates' },
    { id: '54', name: 'Martial Arts' },
    { id: '55', name: 'Running' },
    { id: '56', name: 'Climbing' },
    { id: '57', name: 'Skateboarding' },
    { id: '58', name: 'Scooters' },
    { id: '59', name: 'Drones' },
    { id: '60', name: 'RC Vehicles' },
    { id: '61', name: 'Model Kits' },
    { id: '62', name: 'Action Figures' },
    { id: '63', name: 'Dolls' },
    { id: '64', name: 'Stuffed Animals' },
    { id: '65', name: 'Educational Toys' },
    { id: '66', name: 'Building Toys' },
    { id: '67', name: 'Remote Control Toys' },
    { id: '68', name: 'Science Kits' },
    { id: '69', name: 'Magic Kits' },
    { id: '70', name: 'Robotics' },
    { id: '71', name: 'STEM Toys' },
    { id: '72', name: 'Art & Craft Kits' },
    { id: '73', name: 'Plush Toys' },
    { id: '74', name: 'Ride-On Toys' },
    { id: '75', name: 'Trains' },
    { id: '76', name: 'Slot Cars' },
    { id: '77', name: 'Board Books' },
    { id: '78', name: 'Graphic Novels' },
    { id: '79', name: 'Cookbooks' },
    { id: '80', name: 'Travel Guides' },
    { id: '81', name: 'Biographies' },
    { id: '82', name: 'Self-Help' },
    { id: '83', name: 'Fiction' },
    { id: '84', name: 'Non-Fiction' },
    { id: '85', name: 'Mystery' },
    { id: '86', name: 'Romance' },
    { id: '87', name: 'Science Fiction' },
    { id: '88', name: 'Fantasy' },
    { id: '89', name: 'Thrillers' },
    { id: '90', name: 'Horror' },
    { id: '91', name: 'Poetry' },
    { id: '92', name: 'Comics' },
    { id: '93', name: 'Manga' },
    { id: '94', name: 'Textbooks' },
    { id: '95', name: 'Reference' },
    { id: '96', name: 'Dictionaries' },
    { id: '97', name: 'Encyclopedias' },
    { id: '98', name: 'Atlases' },
    { id: '99', name: 'Yearbooks' },
    { id: '100', name: 'Directories' },
];
  
  export default categories;